namespace app.packets.enums;

public enum OpcodePackets
{
    LOGIN_PLAYER = 1,
    LOGIN_PLAYER_RESPONSE_SUCCESS = 2,
    LOGIN_PLAYER_RESPONSE_ERRO = 3,
        
    DISCONNECT_PLAYER = 4,
    DISCONNECT_PLAYER_RESPONSE = 5,
        
    PLAYER_LOCALIZATION = 6,
    PLAYER_LOCALIZATION_RESPONSE = 7,
        
    UPDATE_CONNECTIONS_RESPONSE = 8
}